version: "3.5"
services:
  traefik:
    hostname: traefik
    image: traefik:latest
    networks:
      - default
      - traefik
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    environment:
      - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/traefik:/etc/traefik
      - ${USERDIR}/docker/shared:/shared
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  traefik:
    name: traefik
    driver: overlay
      #default:
          #driver: bridge
